### ISSUE TITLE
 undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by macbury** [express42-cookbooks/postgresql_lwrp#27]
```
postgresql_user[gse_development] action create
           
           ================================================================================
           Error executing action `create` on resource 'postgresql_user[gse_development]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `empty?' for nil:NilClass
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/postgresql_lwrp/libraries/helpers.rb:79:in `create_user'
           /tmp/kitchen/cache/cookbooks/postgresql_lwrp/providers/user.rb:54:in `block in class_from_file'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
```

My cookbook:
```
postgresql_version      = node['gse']['db']['version'] #9.3
postgresql_cluster_name = node['gse']['db']['cluster'] # gse-main

apt_repository 'pgdg' do
  uri 'http://apt.postgresql.org/pub/repos/apt/'
  components ['main']
  distribution 'trusty-pgdg'
  key 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
  action :add
  deb_src true
end

postgresql postgresql_cluster_name do
  cluster_version postgresql_version
end

databases = data_bag('gse_db')

databases.each do |database_name|
  database = data_bag_item('gse_db', database_name)

  postgresql_user database['user'] do
    in_version postgresql_version
    in_cluster postgresql_cluster_name
    unencrypted_password database['password']
  end

  postgresql_database database_name do
    in_version postgresql_version
    in_cluster postgresql_cluster_name
    owner database['user']
  end

end
```
kitchen.yml
```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[gse::default]
    attributes:
```

Full cookbook:
https://github.com/macbury/gse_cookbook
